const splashTexts = [
      "(Hello World!)",
      "(🙏BLESS🙏)",
      "(Just Monika)",
      "(Welcome to brand new world!)",
      "(Romans 8:18)",
      "(Where you belong)",
      "(Anybody reading these?)",
      "(And you don't seem to understand...)",
      "(I am ballin',I am faded)",
      "(Finding Encarnacion Bechaves)",
      "(See you on Infinity castle)",
      "(LEGO Piece 26047)",
      "(Never type 'nav secret' here (worst mistake I made))",
      "([Bottom text])",
      "(Pan Paka Pan!)",
      "(🍋🍈🍪)",
      "(Made by Aki)",
      "(Made by J.M.C.B)",
      "(🍋🍈🍪🍪🍋🍈🍪🍈🍋)",
      "(Maxx 'C'< Ash blossom < Called by the grave < Crossout designator)",
      "(In this craziness,you gave life...)",
      "(Chicken Jockey)",
      "(Now on Github!)",
      "(My life I trade in for your pain...)",
      "(I am Gundam)",
      "(Just wild beat,Kamuning station)",
      "(We are electric)",
      "(A minute in Manila is 60 seconds in Tokyo)",
      "(Reverse Tokyo to get to Kyoto)",
      "(There is no cow layer)",
      "(Funk soul brother)",
      "(Might play Doom soon)",
      "(Nani ga suki?)",
      "(Up,Up,Down,Down,Left,Right,Left,Right,Select,Start,B,A)",
      "(Classic)",
      "(Everything is awesome)",
      "(Zet hashur)",
      "(Beta!)",
      "(Keeping things interesting as possible)",
      "(Moon breathing,first form: Dark moon,evening palace)",
      "(Life is kyu-kurarin)",
      "(*Insert amen break here*)",
      "(I gently open the door.....)",
      "(349 is a cursed number)",
      "(It's time to duel!)",
      "(Hier kommt die sonne)",
      "(Emu is means smile)",
      "(Thats the wonder, the wonder of U)",
      "(Konnichiwonderhoiii)",
      "(Blue pill or Red pill?)",
      "(Welcome to my OS)",
      "(Zaphkiel: Aleph)",
      "(Feel good)",
      "(Pro tip: You can now click del or home button to navigate.)",
      "(Part 2: Electric boogaloo)",
      "(Color by Technicolor)",
      "(Making great things possible)",
      "(| / | l / || / |_ )",
      "(GUI mode coming soon)",
      "( ͡° ͜ʖ ͡°)",
      "(May music video ba talaga ang Alapaap?)",
      "(Present day,Present time)",
      "(Simulates shell-like OS!)"
];
    const randomizer = Math.floor(Math.random() * splashTexts.length);
    const splashElement = document.getElementById("randMessages");
    splashElement.textContent = splashTexts[randomizer];